Repository getnelson/nelson, pull requests merged in 2018-09, with the labels that each got.

#104 Do not publish documentation on 0.10.x branch
  .buildkite/pipeline.exec.sh
Labels: technical debt

#93 blueprints/templating
  core/src/main/resources/nelson/canopus_cron_job.mustache
  core/src/main/resources/nelson/canopus_job.mustache
  core/src/main/resources/nelson/canopus_service.mustache
  core/src/main/scala/Config.scala
  core/src/main/scala/Datacenter.scala
  core/src/main/scala/Exceptions.scala
  core/src/main/scala/Kubectl.scala
  core/src/main/scala/KubernetesClient.scala
  core/src/main/scala/Nelson.scala
  core/src/main/scala/Workflow.scala
  core/src/main/scala/blueprint/Blueprint.scala
  core/src/main/scala/blueprint/DefaultBlueprints.scala
  core/src/main/scala/blueprint/Render.scala
  core/src/main/scala/blueprint/Template.scala
  core/src/main/scala/health/KubernetesHealthClient.scala
  core/src/main/scala/scheduler/KubernetesHttp.scala
  core/src/main/scala/scheduler/KubernetesShell.scala
  core/src/main/scala/scheduler/NomadHttp.scala
  core/src/main/scala/scheduler/SchedulerOp.scala
  core/src/main/scala/storage/h2.scala
  core/src/main/scala/storage/op.scala
  core/src/main/scala/workflows/Canopus.scala
  core/src/main/scala/workflows/Magnetar.scala
  core/src/main/scala/workflows/Pulsar.scala
  core/src/test/resources/nelson/datacenters-missing-consul.cfg
  core/src/test/resources/nelson/datacenters-missing-domain.cfg
  core/src/test/resources/nelson/datacenters.cfg
  core/src/test/scala/DeploymentMonitorSpec.scala
  core/src/test/scala/DeploymentSpec.scala
  core/src/test/scala/ExpirationPolicySpec.scala
  core/src/test/scala/Fixtures.scala
  core/src/test/scala/InstrumentedNomadClientSpec.scala
  core/src/test/scala/LoadbalancerSpec.scala
  core/src/test/scala/NelsonSuite.scala
  core/src/test/scala/NomadJsonSpec.scala
  core/src/test/scala/SweeperSpec.scala
  core/src/test/scala/TrafficShiftSpec.scala
  core/src/test/scala/blueprint/BlueprintSpec.scala
  http/build.sbt
  http/src/main/scala/plans/Blueprints.scala
Labels: blueprints

#111 Kubernetes/jwt
  core/src/main/scala/InstrumentedVaultClient.scala
  core/src/main/scala/Templates.scala
  core/src/main/scala/Workflow.scala
  core/src/main/scala/vault/http/Http4sVault.scala
  core/src/main/scala/vault/http/json.scala
  core/src/main/scala/vault/op.scala
  core/src/main/scala/vault/policies.scala
  core/src/main/scala/workflows/Magnetar.scala
  core/src/main/scala/workflows/Pulsar.scala
  core/src/test/scala/NelsonSuite.scala
  core/src/test/scala/vault/PoliciesSpec.scala
Labels: vault

#121 Change the default nelson UID inside the container
  core/src/main/resources/nelson/defaults.cfg
  http/build.sbt
  project/plugins.sbt
Labels: technical debt

#124 blueprints/manifest
  core/src/main/scala/Actionable.scala
  core/src/main/scala/Exceptions.scala
  core/src/main/scala/Manifest.scala
  core/src/main/scala/ManifestValidator.scala
  core/src/main/scala/Nelson.scala
  core/src/main/scala/Workflow.scala
  core/src/main/scala/blueprint/Blueprint.scala
  core/src/main/scala/package.scala
  core/src/main/scala/scheduler/KubernetesShell.scala
  core/src/main/scala/scheduler/NomadHttp.scala
  core/src/main/scala/scheduler/SchedulerOp.scala
  core/src/main/scala/workflows/Canopus.scala
  core/src/main/scala/workflows/Magnetar.scala
  core/src/main/scala/workflows/Pulsar.scala
  core/src/main/scala/yaml/ManifestV1Parser.scala
  core/src/test/resources/nelson/manifest.v1.blueprint-missing.yml
  core/src/test/resources/nelson/manifest.v1.everything.yml
  core/src/test/scala/AlertSpec.scala
  core/src/test/scala/Fixtures.scala
  core/src/test/scala/ManifestValidationSpec.scala
  core/src/test/scala/NelsonSuite.scala
  core/src/test/scala/ReleaseDBSpec.scala
  core/src/test/scala/RoutingFixtures.scala
  core/src/test/scala/yaml/ManifestYamlSpec.scala
Labels: blueprints

#128 Stop escalate exploding
  core/src/main/scala/storage/h2.scala
Labels: blueprints

#131 Fix kube JWT
  core/src/main/resources/nelson/defaults.cfg
  core/src/main/scala/Config.scala
  core/src/main/scala/Datacenter.scala
  core/src/main/scala/Workflow.scala
  core/src/main/scala/vault/http/Http4sVault.scala
  core/src/main/scala/vault/op.scala
  core/src/main/scala/workflows/Pulsar.scala
Labels: vault

#132 Fix discarding of the augmented manifest
  core/src/main/scala/ManifestValidator.scala
Labels: blueprints
